AWSTemplateFormatVersion: 2010-09-09
Description: haapi - Scheduler

Parameters:
  Env:
    Type: String

Resources:
  LateFeesEmailScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger sendLateFeesEmail function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: LateFeesScheduler
      ScheduleExpression: "cron(0 8 * * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !Sub '{{resolve:ssm:/haapi/${Env}/execution/role-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.SendLateFeesEmailTriggered'
          Source: 'school.hei.haapi'

  UpdateFeesStatusToLateScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger updateFeesStatusToLate function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: UpdateLateFeesStatusScheduler
      ScheduleExpression: "cron(0 0 * * ? *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !Sub '{{resolve:ssm:/haapi/${Env}/execution/role-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.UpdateFeesStatusToLateTriggered'
          Source: 'school.hei.haapi'

  CheckAttendanceScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger updateFeesStatusToLate function
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: CheckAttendanceScheduler
      ScheduleExpression: "cron(0 */2 ? * MON-SAT *)"
      Target:
        Arn: !Sub '{{resolve:ssm:/haapi/${Env}/eventbridge/bus-arn}}'
        RoleArn: !Sub '{{resolve:ssm:/haapi/${Env}/execution/role-arn}}'
        EventBridgeParameters:
          DetailType: 'school.hei.haapi.endpoint.event.gen.CheckAttendanceTriggered'
          Source: 'school.hei.haapi'